### PR TITLE
Add rocko and master manifests

### PR DESCRIPTION
**Pull request by OYTIS**

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
Seems to work!

**Comment by cajun-rat** [comment]
@EpicNuts Can you quickly test that the build works for R-Pi Quickstart, please?  There should be no need to go through the update process

**Comment by EpicNuts** [comment]
Sorry, didn't manage to reply before leaving for German class. Confirmed the build still works.

**Comment by pattivacek** [comment]
Assigning to the only people I know of with write access.

**Comment by cajun-rat** [comment]
This was merged as part of #18

**Pull request closed without merging**
