### PR TITLE
Added repo config with references to 'thud' releases of layers

### PR DESCRIPTION
**Pull request by codders**

### CODE REVIEW

**Comment by pattivacek** [comment]
Looks like `meta-raspberrypi` and `meta-updater` doesn't have thud branches yet.

**Comment by codders** [comment]
I pushed the branch for meta-updater - that should be there now. For meta-raspberrypi, we could use master or sumo-next for now - what would you prefer?

**Comment by pattivacek** [comment]
> I pushed the branch for meta-updater - that should be there now.

Confirmed, I see it now. Thanks!

> For meta-raspberrypi, we could use master or sumo-next for now - what would you prefer?

I think we don't have a choice, it has to be master (until they release thud).

**Comment by codders** [comment]
Pushed with meta-raspberrypi @ master

**Review by pattivacek — APPROVED** [review]

**Pull request merged**
