### PR TITLE
rocko.xml: Repo manifest for YP release Rocko

### PR DESCRIPTION
**Pull request by leon-anavi**
Manifest for building Poky with Yocto/OE layer
meta-updater for release Rocko.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
This looks fine to me. It looks like @OYTIS made a draft Rocko in https://github.com/advancedtelematic/updater-repo/pull/16, and despite that that was approved over a month ago, it still hasn't been merged. Your version looks more complete to me, but the rest of that PR should still be merged, too.

**Comment by pattivacek** [comment]
Assigning to the only people I know of with write access.

**Comment by leon-anavi** [comment]
Hi @patrickvacek, thank you for the review. I decided to do another GitHub PR although there is #16, because it was easier to update layers based on the pyro.xml. Today I have verified that it works fine by building Poky Rocko and doing end to end update on QEMU.

Best regards, Leon

**Comment by leon-anavi** [comment]
Hi @patrickvacek, @OYTIS, @cajun-rat,

What is the status of this GitHub PR? I has been under review for 3 weeks and in the mean time commit 8143d42dc763aa6011b671fa6fa97b12e300ddc3 was merged.

Thanks,
Leon

**Comment by cajun-rat** [comment]
Hi Leon,

Sorry for the delay getting this merged. I want to be extra careful when merging things that can potentially break our user's first-run experience, and that coupled with a bunch of fire-fighting over the last two weeks has meant that I didn't get this in quickly.

At the end of last week we discovered that we needed to switch the default branch to Pyro, so I took some changes that @OYTIS had been working on (making default.xml a symlink) and merged your rocko.xml manifest with that to make PR #18. That meant we would only need a single QA run for both changes (because this directly affects first-time users, there are a bunch of manual steps in this QA process).

Your work getting rocko to work is not forgotten, and most appreciated!

**Comment by leon-anavi** [comment]
Closed. I have created a separate GitHub PR to align the differences #19.

Best regards, Leon

**Pull request closed without merging**
