### PR TITLE
Default to thud

### PR DESCRIPTION
**Pull request by pattivacek**
Do not merge until the docs are updated appropriately! (See https://github.com/advancedtelematic/aktualizr/pull/1325.)

### CODE REVIEW

**Comment by pattivacek** [comment]
@merltron @tkfu I'd like to merge this, but I don't want to do so until we are confident that anyone using the default understands the implications. Most people using the default now (i.e. rocko) will probably want to re-init their repo to specify `rocko.xml`. Should we document this somewhere?

**Comment by merltron** [comment]
> @merltron @tkfu I'd like to merge this, but I don't want to do so until we are confident that anyone using the default understands the implications. Most people using the default now (i.e. rocko) will probably want to re-init their repo to specify `rocko.xml`. Should we document this somewhere?

@patrickvacek  Sorry to bounce another question back to you - but I again don't know. What would be a scenario where someone would be affected by this? How would we help them make the right decision? Perhaps you could add a draft of what you would like to say?

**Comment by pattivacek** [comment]
@merltron No problem, this is basically the same topic I brought up in the other PR. I'll draft something that covers all of it.

**Comment by pattivacek** [comment]
Rough doc: https://github.com/advancedtelematic/aktualizr/pull/1330

**Comment by pattivacek** [comment]
This will be ready once the changes in https://github.com/advancedtelematic/aktualizr/pull/1330 are live and we feel comfortable with pointing anyone who complains about the change to that doc (https://github.com/advancedtelematic/aktualizr/blob/master/docs/ota-client-guide/modules/ROOT/pages/yocto-release-branches.adoc#using-the-default-manifest on github).

**Comment by pattivacek** [comment]
I think this is ready to merge now that https://docs.ota.here.com/ota-client/latest/build-raspberry.html refers to thud explicitly. If anyone using the default manifest reports a problem about upgrading to thud, and they'd prefer to stay on rocko, then follow the instructions here: https://docs.ota.here.com/ota-client/latest/yocto-release-branches.html#_using_the_default_manifest.

**Review by tkfu — APPROVED** [review]
I pushed a commit with two minor changes: add `-m thud.xml` (and an explanatory comment), plus updated the mega manual link to the thud version of the manual. With that, LGTM.

**Comment by pattivacek** [comment]
@tkfu Thanks. I want to clean up this README a bit anyway, since most of it is redundant with better docs in the portal, but I think your additions are still worthwhile.

**Pull request merged**
